seml:
  executable: hierarchical/pbmc/pbmc_hierarchical.py
  name: pbmc_hierarchical
  output_dir: hierarchical/logs
  project_root_dir: /storage/groups/ml01/workspace/carlo.dedonno/lataq_reproduce
  conda_environment: lataq_cuda
slurm:
  experiments_per_job: 1
  sbatch_options_template: GPU
  sbatch_options:
    mem: 50G          # memory
    cpus-per-task: 2  # num cores
    time: 0-12:00     # max time, D-HH:MM
  max_jobs_per_batch: 8
###### BEGIN PARAMETER CONFIGURATION ######
grid:
  runs:
    type: uniform
    min: 1
    max: 5
    num: 5
  ann_levels: 
    type: choice
    options:
      - [1]
      - [2]
      - [3]
      - [1, 2]
      - [2, 3]
      - [1, 2, 3]