seml:
  executable: benchmarks/svm/svm_rejection_seml.py
  name: svm_rejection
  output_dir: benchmarks/logs
  project_root_dir: /storage/groups/ml01/workspace/carlo.dedonno/lataq_reproduce
  conda_environment: lataq_cuda
slurm:
  experiments_per_job: 1
  sbatch_options_template: CPU
  sbatch_options:
    cpus-per-task: 8
    mem: 100G          # memory
    time: 1-00:00     # max time, D-HH:MM
  #max_jobs_per_batch: 8

###### BEGIN PARAMETER CONFIGURATION ######
grid:
  data: 
    type: choice
    options:
      - pancreas
      - pbmc
      - brain
      - scvelo
      - tumor
      - lung
      #- lung_h