seml:
  executable: hyperopt/embedcvae_seml.py
  name: embedcvae_hyperparam_tuning
  output_dir: hyperopt/logs
  project_root_dir: /storage/groups/ml01/workspace/carlo.dedonno/lataq_reproduce
slurm:
  experiments_per_job: 1
  sbatch_options_template: GPU
  sbatch_options:
    mem: 25G          # memory
    cpus-per-task: 2  # num cores
    time: 0-06:00     # max time, D-HH:MM
  max_jobs_per_batch: 1

###### BEGIN PARAMETER CONFIGURATION ######

fixed:
  n_epochs: 100
  n_pre_epochs: 80

grid:
  data: 
    type: choice
    options:
      - pancreas
      - pbmc
      - brain
      - scvelo
      - tumor
      - lung
      #- lung_h

random:
  samples: 200
  seed: 420
  latent_dim:
    type: choice
    options:
      - 10
      - 20
      - 30
      - 40 
      - 50

  clustering_res: #VERY DATA DEPENDENT
    type: choice
    options:
      - 0.5
      - 1.0
      - 1.5
      - 2.0

  hidden_layers:
    type: randint
    min: 1
    max: 4
    #num: 5
    
  eta:  #weight for landmark loss (both labeled and unlabeled)
    type: choice
    options: 
      - 1
      - 100
      - 1000

  alpha_epoch_anneal:
    type: choice
    options:
      - 1e2
      - 1e4
      - 1e6
  
  loss_metric: 
    type: choice
    options:
      - dist