seml:
  executable: hyperopt/hyperparam_tuning_seml.py
  name: hyperbolic_tuning
  output_dir: hyperopt/logs
  project_root_dir: /storage/groups/ml01/workspace/carlo.dedonno/lataq_reproduce
  conda_environment: lataq_cuda
slurm:
  experiments_per_job: 1
  sbatch_options_template: GPU
  sbatch_options:
    mem: 25G          # memory
    cpus-per-task: 2  # num cores
    time: 0-12:00     # max time, D-HH:MM
  max_jobs_per_batch: 8

###### BEGIN PARAMETER CONFIGURATION ######

fixed:
  n_epochs: 100
  n_pre_epochs: 80

grid:
  data: 
    type: choice
    options:
      - pancreas
      - pbmc
      - brain
      - scvelo
      - tumor
      - lung
      #- lung_h
  model:
    type: choice
    options:
      #- embedcvae
      - tranvae
#random:
#  samples: 100
#  seed: 420
  latent_dim:
    type: choice
    options:
      - 25

  clustering_res: #VERY DATA DEPENDENT
    type: choice
    options:
      - 1.0

  hidden_layers:
    type: choice
    options:
        - 2
    
  eta:  #weight for landmark loss (both labeled and unlabeled)
    type: choice
    options: 
      - 1
      - 10
      - 100
      - 1000

  alpha_epoch_anneal:
    type: choice
    options:
      #- 1e2
      #- 1e4
      - 1e6
  
  loss_metric: 
    type: choice
    options:
      - hyperbolic
      - hyperbolic_log1p
      - dist